language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t Netanelbl10/docker-react -f Dockerfile .

script:
  - docker run -e CI=true Netanelbl10/docker-react npm run test

